// André Luiz Kovalski - Leonardo Matthew Knight

enum Severidade {
	DEBUG,
	WARNING,
	ERROR,
	CRITICAL
};

interface Logger {

	attribute boolean verbose;
  readonly attribute  unsigned short count;

	void log(
		in Severidade severidade,
		in string endereco,
		in unsigned short pid,
		in string hora,
		in string msg
		);

};

